# Generated by Django 5.0.1 on 2024-02-05 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pg_app", "0002_patient_heart_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="age",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(130),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="heart_rate",
            field=models.IntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(280),
                ],
            ),
        ),
    ]
